FROM centos:8
MAINTAINER unknown

RUN dnf -y update && dnf clean all && dnf -y install wget && yum groupinstall "Development Tools"
RUN useradd -m -d /home/user -s /bin/bash user && usermod -a -G mock user
USER user
WORKDIR /home/user

